implement write_bytes for Stdout and Stderr (#329)
* implement write_bytes for Stdout and Stderr

* export functions and add examples

The example compiles, but I get a linker error:

> roc run --linker legacy dup-bytes.roc

roc: /lib64/libtinfo.so.6: no version information available (required by roc)
ld: /tmp/roc_app63Br6T.o: in function `roc_fx_stdout_write_bytes_fastcc_wrapper':
builtins-host:(.text+0xacf6): undefined reference to `roc_fx_stdout_write_bytes'
ld: /tmp/roc_app63Br6T.o: in function `roc_fx_stderr_write_bytes_fastcc_wrapper':
builtins-host:(.text+0xd6b6): undefined reference to `roc_fx_stderr_write_bytes'
thread 'main' panicked at crates/compiler/build/src/program.rs:1037:17:
not yet implemented: linker failed with exit code Some(1)

* add expect script for dup-bytes

* fix script

* let's try with just one example

* fix expect script+tests

* check segfault with valgrind

* try to avoid flaky segfault

* complete test

---------

Co-authored-by: Anton-4 <17049058+Anton-4@users.noreply.github.com>